### ISSUE TITLE
Dependency missing from requirements.txt

### ISSUE THREAD

**Issue by arcum42** [justUmen/Bjornulf_custom_nodes#11]
Since wget is now being imported, it should also be added to the requirements.txt file, so that it's automatically installed, rather then needing to be installed manually.

https://github.com/justUmen/Bjornulf_custom_nodes/blob/20f902f1564e906bade0bef62c88feb1895bc450/API_civitai.py#L16

**Comment by justUmen** [comment]
Hi, thx for the report.
Actually, it isn't used anymore, I have a lot of cleanup to do, probably elsewhere. :)

https://github.com/justUmen/Bjornulf_custom_nodes/commit/38b83ed8f5ab1fa41969bc384e30a8c1b0e12688

**Comment by arcum42** [comment]
No problem, it mostly came up because I had to rebuild my venv recently, and it was failing on that import after re-adding the requirements, so I thought I'd put in a report.

Certainly know the feeling, cleanup-wise.
